In [30]:
#Importing the necessary libraries
import pandas as pd
import numpy as np

In [31]:
#Importing the dataset from this address.Assign it to a variable called iris
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')

In [32]:
iris = df
iris.head()

   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [33]:
# Step 4. Creating columns for the dataset
# 1. sepal_length (in cm)
# 2. sepal_width (in cm)
# 3. petal_length (in cm)
# 4. petal_width (in cm)
# 5. class

iris.columns =['sepal_length (in cm)', 'sepal_width (in cm)', 'petal_length (in cm)', 'petal_width (in cm)','class']
iris

,sepal_length (in cm),sepal_width (in cm),petal_length (in cm),petal_width (in cm),class
0,4.9,3.0,1.4,0.2,Iris-setosa
1,4.7,3.2,1.3,0.2,Iris-setosa
2,4.6,3.1,1.5,0.2,Iris-setosa
3,5.0,3.6,1.4,0.2,Iris-setosa
4,5.4,3.9,1.7,0.4,Iris-setosa
...,...,...,...,...,...
144,6.7,3.0,5.2,2.3,Iris-virginica
145,6.3,2.5,5.0,1.9,Iris-virginica
146,6.5,3.0,5.2,2.0,Iris-virginica
147,6.2,3.4,5.4,2.3,Iris-virginica
148,5.9,3.0,5.1,1.8,Iris-virginica

In [4]:
#Creating columns for the dataset
iris.rename(columns={0:'sepal_length (in cm)',1:'sepal_width (in cm)',2:'petal_length (in cm)',3:'petal_width (in cm)',4:'class'},inplace=True)

In [5]:
#Is there any missing value in the dataframe?
iris.isnull().sum()

5.1            0
3.5            0
1.4            0
0.2            0
Iris-setosa    0
dtype: int64

In [6]:
#Lets set the values of the rows 10 to 29 of the column 'petal_length' to NaN
iris.loc[10:29, ['petal_length (in cm)']] = [np.nan]
iris.head(32)

    5.1  3.5  1.4  0.2  Iris-setosa  petal_length (in cm)
0   4.9  3.0  1.4  0.2  Iris-setosa                   NaN
1   4.7  3.2  1.3  0.2  Iris-setosa                   NaN
2   4.6  3.1  1.5  0.2  Iris-setosa                   NaN
3   5.0  3.6  1.4  0.2  Iris-setosa                   NaN
4   5.4  3.9  1.7  0.4  Iris-setosa                   NaN
5   4.6  3.4  1.4  0.3  Iris-setosa                   NaN
6   5.0  3.4  1.5  0.2  Iris-setosa                   NaN
7   4.4  2.9  1.4  0.2  Iris-setosa                   NaN
8   4.9  3.1  1.5  0.1  Iris-setosa                   NaN
9   5.4  3.7  1.5  0.2  Iris-setosa                   NaN
10  4.8  3.4  1.6  0.2  Iris-setosa                   NaN
11  4.8  3.0  1.4  0.1  Iris-setosa                   NaN
12  4.3  3.0  1.1  0.1  Iris-setosa                   NaN
13  5.8  4.0  1.2  0.2  Iris-setosa                   NaN
14  5.7  4.4  1.5  0.4  Iris-setosa                   NaN
15  5.4  3.9  1.3  0.4  Iris-setosa                   NaN
16  5.1  3.5  1.4  0.3  Iris-setosa                   NaN
17  5.7  3.8  1.7  0.3  Iris-setosa                   NaN
18  5.1  3.8  1.5  0.3  Iris-setosa                   NaN
19  5.4  3.4  1.7  0.2  Iris-setosa                   NaN
20  5.1  3.7  1.5  0.4  Iris-setosa                   NaN
21  4.6  3.6  1.0  0.2  Iris-setosa                   NaN
22  5.1  3.3  1.7  0.5  Iris-setosa                   NaN
23  4.8  3.4  1.9  0.2  Iris-setosa                   NaN
24  5.0  3.0  1.6  0.2  Iris-setosa                   NaN
25  5.0  3.4  1.6  0.4  Iris-setosa                   NaN
26  5.2  3.5  1.5  0.2  Iris-setosa                   NaN
27  5.2  3.4  1.4  0.2  Iris-setosa                   NaN
28  4.7  3.2  1.6  0.2  Iris-setosa                   NaN
29  4.8  3.1  1.6  0.2  Iris-setosa                   NaN
30  5.4  3.4  1.5  0.4  Iris-setosa                   NaN
31  5.2  4.1  1.5  0.1  Iris-setosa                   NaN

In [7]:
#Substituting the NaN values to 1.0
iris['petal_length (in cm)'].iloc[9:29].replace(np.nan,1.0,inplace=True)
iris['petal_length (in cm)'].iloc[9:29]

9     1.0
10    1.0
11    1.0
12    1.0
13    1.0
14    1.0
15    1.0
16    1.0
17    1.0
18    1.0
19    1.0
20    1.0
21    1.0
22    1.0
23    1.0
24    1.0
25    1.0
26    1.0
27    1.0
28    1.0
Name: petal_length (in cm), dtype: float64

In [20]:
#Deleting the index class
iris.drop('index',axis=1,inplace=True)
iris

    5.1  3.5  1.4  0.2  Iris-setosa  petal_length (in cm)
0   5.4  3.7  1.5  0.2  Iris-setosa                   1.0
1   4.8  3.4  1.6  0.2  Iris-setosa                   1.0
2   4.8  3.0  1.4  0.1  Iris-setosa                   1.0
3   4.3  3.0  1.1  0.1  Iris-setosa                   1.0
4   5.8  4.0  1.2  0.2  Iris-setosa                   1.0
5   5.7  4.4  1.5  0.4  Iris-setosa                   1.0
6   5.4  3.9  1.3  0.4  Iris-setosa                   1.0
7   5.1  3.5  1.4  0.3  Iris-setosa                   1.0
8   5.7  3.8  1.7  0.3  Iris-setosa                   1.0
9   5.1  3.8  1.5  0.3  Iris-setosa                   1.0
10  5.4  3.4  1.7  0.2  Iris-setosa                   1.0
11  5.1  3.7  1.5  0.4  Iris-setosa                   1.0
12  4.6  3.6  1.0  0.2  Iris-setosa                   1.0
13  5.1  3.3  1.7  0.5  Iris-setosa                   1.0
14  4.8  3.4  1.9  0.2  Iris-setosa                   1.0
15  5.0  3.0  1.6  0.2  Iris-setosa                   1.0
16  5.0  3.4  1.6  0.4  Iris-setosa                   1.0
17  5.2  3.5  1.5  0.2  Iris-setosa                   1.0
18  5.2  3.4  1.4  0.2  Iris-setosa                   1.0
19  4.7  3.2  1.6  0.2  Iris-setosa                   1.0

In [12]:
#Seting the first 3 rows as NaN
iris.iloc[0:3]=np.nan
iris

     5.1  3.5  1.4  0.2     Iris-setosa  petal_length (in cm)
0    NaN  NaN  NaN  NaN             NaN                   NaN
1    NaN  NaN  NaN  NaN             NaN                   NaN
2    NaN  NaN  NaN  NaN             NaN                   NaN
3    5.0  3.6  1.4  0.2     Iris-setosa                   NaN
4    5.4  3.9  1.7  0.4     Iris-setosa                   NaN
..   ...  ...  ...  ...             ...                   ...
144  6.7  3.0  5.2  2.3  Iris-virginica                   NaN
145  6.3  2.5  5.0  1.9  Iris-virginica                   NaN
146  6.5  3.0  5.2  2.0  Iris-virginica                   NaN
147  6.2  3.4  5.4  2.3  Iris-virginica                   NaN
148  5.9  3.0  5.1  1.8  Iris-virginica                   NaN

[149 rows x 6 columns]

In [13]:
#Deleting the rows that have NaN
iris.dropna(inplace=True)

In [14]:
#Reseting the index so it begins with 0 again
iris.reset_index(inplace=True)

In [15]:
iris

    index  5.1  3.5  1.4  0.2  Iris-setosa  petal_length (in cm)
0       9  5.4  3.7  1.5  0.2  Iris-setosa                   1.0
1      10  4.8  3.4  1.6  0.2  Iris-setosa                   1.0
2      11  4.8  3.0  1.4  0.1  Iris-setosa                   1.0
3      12  4.3  3.0  1.1  0.1  Iris-setosa                   1.0
4      13  5.8  4.0  1.2  0.2  Iris-setosa                   1.0
5      14  5.7  4.4  1.5  0.4  Iris-setosa                   1.0
6      15  5.4  3.9  1.3  0.4  Iris-setosa                   1.0
7      16  5.1  3.5  1.4  0.3  Iris-setosa                   1.0
8      17  5.7  3.8  1.7  0.3  Iris-setosa                   1.0
9      18  5.1  3.8  1.5  0.3  Iris-setosa                   1.0
10     19  5.4  3.4  1.7  0.2  Iris-setosa                   1.0
11     20  5.1  3.7  1.5  0.4  Iris-setosa                   1.0
12     21  4.6  3.6  1.0  0.2  Iris-setosa                   1.0
13     22  5.1  3.3  1.7  0.5  Iris-setosa                   1.0
14     23  4.8  3.4  1.9  0.2  Iris-setosa                   1.0
15     24  5.0  3.0  1.6  0.2  Iris-setosa                   1.0
16     25  5.0  3.4  1.6  0.4  Iris-setosa                   1.0
17     26  5.2  3.5  1.5  0.2  Iris-setosa                   1.0
18     27  5.2  3.4  1.4  0.2  Iris-setosa                   1.0
19     28  4.7  3.2  1.6  0.2  Iris-setosa                   1.0